name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn qiskit qiskit-aer matplotlib numpy pytest flake8 black
      - name: Lint
        run: |
          flake8 .
          black --check .
      - name: Tests
        run: pytest -q
